# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='user_id',
            new_name='user',
        ),
    ]
